# Generated by Django 3.2.9 on 2021-12-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spado_ubuntu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(default='default/default_5.jpg', upload_to='images/profile_pics/'),
        ),
    ]
