# Generated by Django 3.2.9 on 2022-01-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spado_ubuntu', '0005_alter_account_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(default='default/default_3.jpg', upload_to='images/profile_pics/'),
        ),
    ]
