# Generated by Django 3.2.9 on 2022-01-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spado_ubuntu', '0009_auto_20220123_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(default='default/default_3.jpg', upload_to='images/profile_pics/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/posts/images_1 %y/%m/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/posts/images_2 %y/ %m/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/posts/images_3 %y/ %m/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='images/posts/images_4 %y/ %m/'),
        ),
    ]
