# Generated by Django 3.2.9 on 2022-02-13 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spado_ubuntu', '0018_alter_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spado_ubuntu.comment'),
        ),
    ]
