# Generated by Django 3.2.9 on 2022-02-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spado_ubuntu', '0020_auto_20220213_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, to='spado_ubuntu.Comment'),
        ),
    ]
