# Generated by Django 3.2.9 on 2022-02-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spado_ubuntu', '0021_alter_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(default='Working', max_length=12),
        ),
        migrations.AddField(
            model_name='account',
            name='status_indicator',
            field=models.CharField(default='Available', max_length=15),
        ),
    ]
